// siempre es igual igual a

var tuSigno = prompt('Escribe tu signo zodiacal').toLowerCase();

switch(tuSigno){
    case 'aries':
        alert('ARIES: Será un año muy especial, porque influirá fuertemente en la familia. Luego, ser tan independiente, se contrapone con la gran vida social que harás y con la vida en pareja o con la idea de atarse a alguien. Esta misma actitud independiente, favorece a tu salud, porque al estar centrado en ti, significa que te cuidarás más. La configuración astral favorece los cambios drásticos y sorpresivos constantes, que sabrás torear y afrontar correctamente. Lo cual te hará estar muy pendiente de todo y muy en tensión');
        break;
    case 'tauro':
        alert('TAURO: A ti te afectarán lo 2 eclipses solares, especialmente en el amor. La espiritualidad y filosofar sobre la vida, serán lo más importante. Sacarás una nueva visión de las cosas y un cambio de actitud. Prevalecerá lo intelectual ante lo frívolo. Los cambios repentinos surgirán cada dos por tres y temblarás de miedo, pero aprenderás a aceptar los cambios radicales e inesperados sin miedo y te sentirás cómodo con ellos. Serán cambios positivos.');
        break;
    case 'geminis':
        alert('GEMINIS: Será un año muy duro, pero merecerá la pena vivirlo, por el gran avance que harás. Romperás con un montón de cosas y personas en tu vida, para convertirte en la persona, que siempre has soñado ser. Puedes tener experiencias con la muerte también, que te harán reaccionar y dar otro sentido a tu vida. Tu libido estará por las nubes y expresarás el sexo de otra forma. Cambio en tu escala de valores. Puedes recibir una herencia o administrarla. Lo que más feliz te hará será el aumento salarial, los cambios que realizarás en tu vida, los estudios superiores, los amigos, los viajes al extranjero.');
        break;
    case 'cancer':
        alert('CANCER: Será un año muy especial. Vas a tener un año muy interesante. Bastante estresante, pero muy bueno, con cambios positivos. Será un año de cambios, problemas y sacudidas, porque tendrás lugar 6 eclipses: 4 lunares y 2 solares. La Luna es el planeta de Cáncer, por lo tanto te va a afectar mucho. Este año vas a tener, que dorar la píldora a los demás para poder conseguir todo lo que quieras. Tú no podrás hacerlo directamente, tendrás que pedirlo y conseguir, que te lo hagan. Podrías perder la amistad a algunos amigos. Tu salud no es muy buena y tu trabajo te agotará, tendrás que cuidarte más de lo que quieres. El cambio de estrategia que harás en lo profesional, te va a tomar mucho tiempo y muchas energías. A pesar de lo complicado del año, te lo tomarás bien porque la economía y el éxito con el sexo opuesto te sonreirán, te compensará');
        break;
    case 'leo':
        alert('LEO: Será un año muy especial. Cambio en el estilo de vida, para conseguir sentirte como tú quieres sentirte: en forma y con energía. El trabajo será muy ajetreado, con mucho estrés, pero importante también para ti. Te relacionarás con gente importante y poderosa y vivirás cambios importantes dentro del trabajo, aunque positivos. Podría ser que empezarás a salir con alguien del trabajo o relacionado con tu trabajo. No será fácil y tu vida sentimental y sexual cambian. Gran evolución espiritual y cambio de enfoque tu vida, gracias a los 4 eclipses lunares que se darán en tu Casa 12. Se resuelve a tu favor un Juicio que tienes pendiente. Los estudios te irán muy bien.');
        break;
    case 'virgo':
        alert('VIRGO: Será un año muy especial. La salud será muy buena y te sentirás fuerte y poderoso. Las ganas de divertirte y ser feliz serán tu lema este año y los serás, especialmente junto a tus hijos. El trabajo se convertirá en algo súper especial para ti y destacarás entre todos tus compañeros, a los ojos de tus superiores. Aumento salarial y ésito profesional. Además, lo pasarás muy bien trabajando. El 2º semestre vivirás una transformación personal y sexual. Otra forma de enfocar y expresar tu deseo sexual. El amor cambia también, ya que te atraerán otro tipo de personas más espirituales e idealista, con quienes poder mantener otro tipo de conversaciones, sobre arte. Literatura. Los eclipses lunares, 4 en total, afectarán a tus amigos y tendrás que ayudarles.');
        break;
    case 'libra':
        alert('LIBRA: Será un año muy especial. Es un año en el, que tendrán lugar 4 exlipses de Luna y 2 de Sol. Esto hace, que en tu profesión habrán muchos cambios y problemas, por resolver. Trabajar para preparar tu futuro profesional. Esto no significa, que sea lo más importante del año, pero tendrás que afrontar y resolverlo para seguir adelante. Tus hijos, tu familia serán lo más importante del año para ti. En el sexo habrá cambios también y querrás innovar y tomártelo de otra forma, la cual te llevará a una evolución personal. La salud será regular y tendrás, que estar cuidándote todo el año. El amor será importante, será más aventurero y en Junio podrías conocer al amor de tu vida. Tu vida social será muy activa y tendrás ocasión de hacer nuevos amigos y una nueva pareja. En Primavera y Verano se ven varios viajes al extranjero.');
        break;
    case 'escorpio':
        alert('ESCORPIO: Será un año muy especial. La familia , el hogar y el equilibrio emocional serán muy importantes y los buscarás. Pero la intelectualidad y la comunicación serán lo más importante. La salud será buena todo el año. De dinero excelente, ya que ganarás más dinero, pero a parte no te costará mucho lograrlo. Los estudiantes de secuandaria bien, pero los universitarios sufrirán todo tipo de bloqueos, problemas, cambios, contratiempos. El trabajo irá muy bien, especialmente si está relacionado con la comunicación. Problemas con los viajes durante los eclipses lunares. Tu forma de entender la religión cambiará y también te vuelves más espiritual. El amor quizás sea lo peor este año, pero no porque no vayas a salir con nadie, si no porque saldrás con varios y aunque emocionante, será muy inestable. Crisis en la pareja, si la tienes.');
        break;
    case 'sagitario':
        alert('SAGITARIO: Será un año muy especial. Este año 2020 serás una persona distinta, te tomarás la vida con seriedad y te esforzarás mucho, para que tu trabajo y tu forma de ganar el dinero. Adquieres más responsabilidades y vas a mover cielo y tierra, para crear nuevos negocios o vías de ingresos. Aún así el trabajo será inestable. Este año ganará mucha fuerza la parte de la familia, el bienestar, los hijos y el dinero, porque te sentirás más importante, por el hecho de poder procurarles una mayor estabilidad económica. La salud será buena todo el año, pero porque tú te encargarás de ir probando nuevos métodos de alimentación y estilo de vida. Si amor no será tan importante este año. Esto no significa que no puedas tener pareja o empezar una nueva, simplemente no será importante. Evolución espiritual debido a la muerte y la transformación');
        break;
    case 'capricornio':
        alert('CAPRICORNIO: Será un año muy especial. Este año 2020 serás una persona distinta, te tomarás la vida con seriedad y te esforzarás mucho, para que tu trabajo y tu forma de ganar el dinero. Adquieres más responsabilidades y vas a mover cielo y tierra, para crear nuevos negocios o vías de ingresos. Aún así el trabajo será inestable. Este año ganará mucha fuerza la parte de la familia, el bienestar, los hijos y el dinero, porque te sentirás más importante, por el hecho de poder procurarles una mayor estabilidad económica. La salud será buena todo el año, pero porque tú te encargarás de ir probando nuevos métodos de alimentación y estilo de vida. Si amor no será tan importante este año. Esto no significa que no puedas tener pareja o empezar una nueva, simplemente no será importante. Evolución espiritual debido a la muerte y la transformación');
        break;
    case 'acuario':
        alert('ACUARIO: Será un año muy especial. A ti te afectarán 5 de ellos en la salud. Lo más importante del año serán el enorme progreso personal y espiritual que realizarás, el cual te beneficiará en tus finanzas. Ya llevas muchos año en los que el dinero no es problema, para ti. Pero este será todavía menor. El amor seguirá como está, con su rutina sin demasiadas emociones. Al igual que tu vida social. No te interesará demasiado, esforzarte por salir cuando en realidad te apetece otro cosa. Para ti primara, hacer un mejor aprovechamiento del tiempo. Laboralmente te irá muy bien en general y en especial a los que se dediquen a temas de comunicación como profesores, perioristas, publicistas, vendedores, escritores...');
        break;
    case 'piscis':
        alert('PISCIS: A tu familia, a quienes les cambiará la vida. Profesionalmente has llegado a lo más alto y tu reputación profesional te precede. Tu vida social está siendo muy activa, pero quizás este año destaca por dedicarte a los amigos íntimos por un lado y por el otro, por mantener muchas relaciones laborales fuera de tu trabajo. El dinero te irá fenomenal y ganarás mucho más que el año anterior. Puedes considerarte afortunado. Tu evolución personal pasará por un trabajo de autoconcinciación, de humildad, porque te darás cuenta, que tu éxito profesional te lleva cada vez más a moverte con gente muy poderosa, importante y has pasado a formar parte de una élite, que te aleja de la realidad.');
        break;
    default:
        alert('No hay signo zodiacal para ti');
}